# Generated by Django 4.2.6 on 2023-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('capa', models.FileField(upload_to='capa')),
                ('duracao', models.IntegerField()),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
    ]
