# Generated by Django 4.2.6 on 2024-01-31 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_category_filmregistration_delete_cadastro_filmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmregistration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='category_movie', to='filmes.category'),
        ),
    ]
