# Generated by Django 4.2.6 on 2024-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filmregistration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmregistration',
            name='cover',
            field=models.FileField(upload_to='cover'),
        ),
    ]
