# Generated by Django 4.2.6 on 2024-02-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_alter_filmregistration_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
